//! Characterization test: the hand-written two-pass IP scanner must reproduce Python's
//! `IPPortPatternLine` and `IPPortPatternGlobal` output exactly.
//!
//! The oracle (`tests/ip_scan_oracle.json`) was generated by running proxybroker2's actual
//! compiled regexes over representative inputs — it is ground truth, not a guess. Rust's
//! `regex` crate cannot compile `IPPortPatternGlobal` (it uses lookahead), so the scanner
//! is hand-written; this test is what proves the rewrite is faithful.

use proxybroker::parse::{find_addrs_global, find_addrs_line};
use serde::Deserialize;

#[derive(Deserialize)]
struct Case {
    input: String,
    line: Vec<Vec<String>>,
    global_: Vec<Vec<String>>,
}

fn oracle() -> Vec<Case> {
    let raw = include_str!("ip_scan_oracle.json");
    serde_json::from_str(raw).expect("oracle json parses")
}

/// Python `findall` returns `(ip, port)` tuples with `''` for an unmatched port group.
/// Our scanner returns `(String, String)` with an empty string for the same.
fn as_pairs(rows: &[Vec<String>]) -> Vec<(String, String)> {
    rows.iter()
        .map(|r| (r[0].clone(), r.get(1).cloned().unwrap_or_default()))
        .collect()
}

#[test]
fn line_scanner_matches_python_oracle() {
    for c in oracle() {
        let got = find_addrs_line(&c.input);
        let want = as_pairs(&c.line);
        assert_eq!(got, want, "line scan of {:?}", c.input);
    }
}

#[test]
fn global_scanner_matches_python_oracle() {
    for c in oracle() {
        let got = find_addrs_global(&c.input);
        let want = as_pairs(&c.global_);
        assert_eq!(got, want, "global scan of {:?}", c.input);
    }
}
